version: "3.9"
services:
  server:
    image: scrap_server_nodejs
    volumes:
      - ./js:/home/node/app:Z
    command: node index.js
    restart: on-failure:100

  client:
    depends_on:
      - server
    image: scrap_client_jupyter
    volumes:
      - ./data:/home/jovyan/app/data:Z
      - ./bin:/home/jovyan/app/bin:Z
      - ./lib:/home/jovyan/app/lib:Z
    command: wait-for-it.sh server:8888 -- python bin/01_coleta.py
    # command: python bin/01_coleta.py
    restart: on-failure:100
